version: '3'
services:
  mazda_be:
    container_name: mazda_be_container
    build:
      context: ./Mazda_BE
      dockerfile: Dockerfile
    ports:
      - "5217:443"
    networks:
      - mazda_network
networks:
  mazda_network:
    name: mazda_custom_network
    driver: bridge

volumes:
  mazda_db_data:
