version: '3'
services:
  nginx:
    container_name: nginx_backend
    build:
      context: ./
      dockerfile: Dockerfile    
    restart: always  
  mazda_be:
    container_name: mazda_be
    build:
      context: ./Mazda_BE
      dockerfile: Dockerfile
    ports:
      - "1131:80"
    networks:
      - mazda_network
networks:
  mazda_network:
    name: mazda_custom_network
    driver: bridge

volumes:
  mazda_db_data:
